# Generated by Django 3.2 on 2021-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
