# Generated by Django 3.2 on 2021-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20211105_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='check_out',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.bookinginfo')),
            ],
        ),
    ]
