# Generated by Django 3.2 on 2021-11-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211105_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.hotelroom'),
        ),
    ]
